name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build application
      run: mvn clean package -DskipTests
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          # Stop current application
          cd /home/ubuntu/mitra
          if [ -f stop.sh ]; then
            ./stop.sh
          fi
          
          # Create backup
          if [ -f mitra-0.0.1-SNAPSHOT.jar ]; then
            mv mitra-0.0.1-SNAPSHOT.jar mitra-backup-$(date +%Y%m%d-%H%M%S).jar
          fi
          
    - name: Copy JAR to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "target/mitra-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/mitra/"
        strip_components: 1
        
    - name: Start application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/mitra
          chmod +x start.sh stop.sh
          ./start.sh
          
          # Wait and verify
          sleep 30
          if curl -f http://localhost:8080/ > /dev/null 2>&1; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - check logs"
            tail -20 logs/mitra.log
            exit 1
          fi